language: node_js

dist: trusty
sudo: false

branches:
  only:
    - dev

deploy:
  skip_cleanup: true
  provider: firebase
  token: 
    secure: "1//03UrKAVdHn-9yCgYIARAAGAMSNwF-L9Irqinx7k2eBrgHr6DHB_7-ScgGGHss1KKW95DMpkZjNl9b5F6xw8XqzJMFVN2QSN0n1Zo"
