name: Build and Lint
'on':
  pull_request:
    branches:
      - '*_dev'
  push:
    branches:
      - '*_dev'
jobs:
  all_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.DOTENVFILE }}" > .env
      - run: echo "${{ secrets.DOTENVDOTPRODFILE }}" > .env.prod
      - run: echo "${{ secrets.DOTFIREBASERCFILE }}" > .firebaserc
      - run: 'yarn install'
      - run: 'yarn nx run-many --target=lint --all --parallel'
      - run: 'yarn nx run-many --target=build --all --parallel --configuration=production'