name: Backend and integration tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install required deps for action
      - name: Install Dependencies
        run: yarn install

      # Install Nx
      #- name: Install Dependencies
      #  run: yarn add nx

      # Finally, run our tests
      
      - name: Start Emulator
        run: |
          yarn start:api:dev &
          # Wait for the first emulator to be ready
          while ! curl -s http://localhost:5005/health &> /dev/null; do sleep 5; done
          yarn start:emulators:imported &
          # Wait for the second emulator to be ready
          while ! curl -s http://localhost:5001/health &> /dev/null; do sleep 5; done
          yarn test:api
