name: Backend and integration tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install required deps for action
      - name: Install Dependencies
        run: yarn install

      # Install Nx
      #- name: Install Dependencies
      #  run: yarn add nx

      # Finally, run our tests
      - name: run Tests
        run: |
          yarn start:api:dev
          yarn start:emulators:imported
          yarn test:api