name: Continous Development of Develop on Merge (CD)
on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    enviroment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Temporary .env
        run: |
          touch .env
          echo ${{secrets.ENV_FILE}} >> .env

      - name: Install Dependencies
        run: yarn install --frozen-lockfile 
        
      - name: Build Application
        run: yarn build:app:dev

      - name: Deploy Development Version
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COS301_MINIPROJECT }}'
          channelId: live
          projectId: cos301-miniproject-2023-b1f6d