name: Deploy to Dev Firebase Hosting without preview on merge
'on':
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create .env file
        env:
          NX_FIREBASE_USE_EMULATORS: ${{ secrets.NX_FIREBASE_USE_EMULATORS }}
          NX_FIREBASE_API_KEY: ${{ secrets.NX_FIREBASE_API_KEY }}
          NX_FIREBASE_AUTH_DOMAIN: ${{ secrets.NX_FIREBASE_AUTH_DOMAIN }}
          NX_FIREBASE_DATABASE_URL: ${{ secrets.NX_FIREBASE_DATABASE_URL }}
          NX_FIREBASE_PROJECT_ID: ${{ secrets.NX_FIREBASE_PROJECT_ID }}
          NX_FIREBASE_STORAGE_BUCKET: ${{ secrets.NX_FIREBASE_STORAGE_BUCKET }}
          NX_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NX_FIREBASE_MESSAGING_SENDER_ID }}
          NX_FIREBASE_APP_ID: ${{ secrets.NX_FIREBASE_APP_ID }}
          NX_FIREBASE_MEASUREMENT_ID: ${{ secrets.NX_FIREBASE_MEASUREMENT_ID }}
          FIRESTORE_EMULATOR_HOST: ${{ secrets.FIRESTORE_EMULATOR_HOST }}
        run: |
          cat <<EOF > .env
          NX_ENVIRONMENT=development
          NX_FIREBASE_USE_EMULATORS="$NX_FIREBASE_USE_EMULATORS"
          NX_FIREBASE_API_KEY="$NX_FIREBASE_API_KEY"
          NX_FIREBASE_AUTH_DOMAIN="$NX_FIREBASE_AUTH_DOMAIN"
          NX_FIREBASE_DATABASE_URL="$NX_FIREBASE_DATABASE_URL"
          NX_FIREBASE_PROJECT_ID="$NX_FIREBASE_PROJECT_ID"
          NX_FIREBASE_STORAGE_BUCKET="$NX_FIREBASE_STORAGE_BUCKET"
          NX_FIREBASE_MESSAGING_SENDER_ID="$NX_FIREBASE_MESSAGING_SENDER_ID"
          NX_FIREBASE_APP_ID="$NX_FIREBASE_APP_ID"
          NX_FIREBASE_MEASUREMENT_ID="$NX_FIREBASE_MEASUREMENT_ID"
          FIRESTORE_EMULATOR_HOST="$FIRESTORE_EMULATOR_HOST"
          EOF

          echo "cat .env"

      - name: Install deps and build
        run: yarn install --frozen-lockfile && yarn build:app:dev

      - name: Deploy and host
        uses: FirebaseExtended/action-hosting-deploy@v0
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ secrets.NX_FIREBASE_PROJECT_ID }}'
