name: Deploy Develop Cloud Functions (CD)
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Production Functions
        run: npx firebase-tools use development && npx firebase-tools deploy -only=functions --tocken "${{ secrets.FIREBASE_TOKEN }}"