name: Deploy Production Functions on Merge (CD)
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Temporary SA Key JSON
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COS301_MINIPROJECT_2023_B1F6D }}' > $HOME/gcloud.json

      - name: Deploy Develop Cloud Functions
        run: npx firebase-tools use production && export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json