name: Deploy Develop Functions on Merge (CD)
on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Temporary SA Key JSON
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COS301_MINIPROJECT_GR9_D_46DED }}' > $HOME/gcloud.json

      - name: Deploy Develop Cloud Functions
        run: npx firebase-tools use development && export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json