name: Host Develop on PR (CD)
on:
  pull_request:
    branches:
      - develop

jobs:
  build_and_preview:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Temporary .env
        run: |
          touch .env
          echo ${{secrets.ENV_FILE}} >> .env
      
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile 
        
      - name: Build Application
        run: yarn build:app:dev

      - name: Preview Development Version
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: >-
            ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COS301_MINIPROJECT_GR9_D_46DED }}
          projectId: cos301-miniproject-gr9-d-46ded