name: Linter
on: push
jobs: 
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Linter
        #uses: github/super-linter@v3.17.0
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: dev
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
