
name: Check lint of code before commit
on:
  push:
      branches:
          - main
  pull_request:
    branches: 
        - main
jobs:
  linting:
    name: Run Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install --frozen-lockfile
      - run: yarn nx run-many --target=lint
    


