

name: Check lint of code before commit
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  name: Run lint check
  runs-on: ubuntu-latest

  steps:
    -uses: actions/checkout@v2
    -uses: actions/setup-node@v1
    with:
        node-version: 18.15.0
    -run: yarn install --frozen-lockfile
    -run: yarn nx run-many --target=lint
    

    


