name: Linter
on: [push, pull_request]
jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -name: ts-standard
       run: 
      - name: Run Linter
        #uses: github/super-linter@v3.17.0
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_HTML: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
