name: Deploy to Firebase on push
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env.prod
        run: echo ${{ secrets.FIREBASE_CONFIG }} > .env.prod

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build App
        run: |
          source .env.prod
          yarn build:app:prod

      - name: Build API
        run: |
          source .env.prod
          yarn build:api:prod
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P cos-301-memory-lane --only hosting,firestore,functions,storage
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
